import * as T from './three.module.js';
// Bake only immutable meshes. The caller explicitly excludes all animated objects.
export function batchStatic(root,exclude=new Set(),ownedGeometries=null){
 root.updateWorldMatrix(true,true);const inverse=root.matrixWorld.clone().invert(),groups=new Map();let before=0,after=0;
 root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||Array.isArray(o.material)||o.material.transparent||!o.visible)return;for(let p=o;p&&p!==root.parent;p=p.parent)if(exclude.has(p))return;const g=o.geometry;if(!g.attributes.position||!g.attributes.normal||Object.keys(g.attributes).some(k=>!['position','normal','uv'].includes(k)))return;const key=[o.material.uuid,o.castShadow,o.receiveShadow,!!g.attributes.uv].join(':');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o);});
 for(const meshes of groups.values()){before+=meshes.length;if(meshes.length<2){after++;continue;}let vertices=0,indices=0;for(const m of meshes){vertices+=m.geometry.attributes.position.count;indices+=m.geometry.index?.count||m.geometry.attributes.position.count;}const pos=new Float32Array(vertices*3),norm=new Float32Array(vertices*3),uv=meshes[0].geometry.attributes.uv?new Float32Array(vertices*2):null,idx=new Uint32Array(indices);let vertexOffset=0,indexOffset=0;const v=new T.Vector3(),n=new T.Vector3();
 for(const m of meshes){const g=m.geometry,matrix=inverse.clone().multiply(m.matrixWorld),normalMatrix=new T.Matrix3().getNormalMatrix(matrix),count=g.attributes.position.count;for(let i=0;i<count;i++){v.fromBufferAttribute(g.attributes.position,i).applyMatrix4(matrix);n.fromBufferAttribute(g.attributes.normal,i).applyNormalMatrix(normalMatrix);v.toArray(pos,(vertexOffset+i)*3);n.toArray(norm,(vertexOffset+i)*3);if(uv){uv[(vertexOffset+i)*2]=g.attributes.uv.getX(i);uv[(vertexOffset+i)*2+1]=g.attributes.uv.getY(i);}}const len=g.index?.count||count;for(let i=0;i<len;i++)idx[indexOffset++]=vertexOffset+(g.index?g.index.getX(i):i);vertexOffset+=count;}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(pos,3));g.setAttribute('normal',new T.BufferAttribute(norm,3));if(uv)g.setAttribute('uv',new T.BufferAttribute(uv,2));g.setIndex(new T.BufferAttribute(idx,1));g.computeBoundingSphere();const combined=new T.Mesh(g,meshes[0].material);combined.castShadow=meshes[0].castShadow;combined.receiveShadow=meshes[0].receiveShadow;root.add(combined);ownedGeometries?.add(g);const retired=new Set();for(const m of meshes){m.removeFromParent();retired.add(m.geometry);}for(const old of retired){old.dispose();ownedGeometries?.delete(old);}after++;
 }
 return{before,after};
}
