// Deterministic track and fixed-step simulation. No renderer or network dependency.
export function random(seed){let a=2166136261;for(const c of String(seed))a=Math.imul(a^c.charCodeAt(0),16777619);return()=>{a+=0x6D2B79F5;let t=Math.imul(a^a>>>15,1|a);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296}}
export const TAU=Math.PI*2;
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
export function track(seed,smoothing=1){const r=random(seed), phases=[r()*TAU,r()*TAU,r()*TAU],amp=[.08+r()*.06,.035+r()*.035,.012+r()*.02],n=240,points=[];const rx=47+r()*8,rz=36+r()*9;for(let i=0;i<n;i++){const t=i/n*TAU;let f=1;for(let k=0;k<3;k++)f+=smoothing*amp[k]*Math.sin((k+2)*t+phases[k]);points.push({x:Math.cos(t)*rx*f,z:Math.sin(t)*rz*f});}for(let i=0;i<n;i++)for(let j=i+20;j<n;j++){if(n-j+i<20)continue;if(Math.hypot(points[i].x-points[j].x,points[i].z-points[j].z)<18&&smoothing>.001)return track(seed,smoothing*.5);}let length=0;for(let i=0;i<n;i++){const p=points[i],q=points[(i+1)%n];p.dx=q.x-p.x;p.dz=q.z-p.z;p.len=Math.hypot(p.dx,p.dz);p.s=length;length+=p.len;p.heading=Math.atan2(p.dz,p.dx);p.nx=-p.dz/p.len;p.nz=p.dx/p.len;}return{seed,points,length,width:11,n};}
export function nearest(t,x,z){let bestDistance=Infinity,bestIndex=0,bestU=0,bestX=0,bestZ=0;for(let i=0;i<t.n;i++){const p=t.points[i],u=clamp(((x-p.x)*p.dx+(z-p.z)*p.dz)/(p.len*p.len),0,1),qx=p.x+p.dx*u,qz=p.z+p.dz*u,dx=x-qx,dz=z-qz,distance=dx*dx+dz*dz;if(distance<bestDistance){bestDistance=distance;bestIndex=i;bestU=u;bestX=qx;bestZ=qz;}}const p=t.points[bestIndex];return{distance:Math.sqrt(bestDistance),x:bestX,z:bestZ,index:bestIndex,s:p.s+p.len*bestU,heading:p.heading,nx:p.nx,nz:p.nz};}
export function at(t,s){s=((s%t.length)+t.length)%t.length;const p=t.points.find((p,i)=>s<p.s+p.len||i===t.n-1),u=(s-p.s)/p.len;return{x:p.x+p.dx*u,z:p.z+p.dz*u,heading:p.heading,nx:p.nx,nz:p.nz};}
export function createCars(t,color,calm=true,aggressive=true,secondColor=null){const roster=[{color,name:'Ты',kind:'player'}];if(secondColor)for(const color of (Array.isArray(secondColor)?secondColor:[secondColor]))roster.push({color,name:'',kind:'player'});if(calm)roster.push({color:'#16c7b7',name:'Виталик',kind:'calm'});if(aggressive)roster.push({color:'#a855f7',name:'Вадя',kind:'aggressive'});return roster.map((r,i)=>{const s=5-Math.floor(i/2)*4,p=at(t,s),lane=(i%2?1:-1)*2;return{...r,id:i,x:p.x+p.nx*lane,z:p.z+p.nz*lane,vx:0,vz:0,heading:p.heading,startS:s,lastS:(s+t.length)%t.length,progress:0,lap:0,finished:false,finishTime:0,stuck:0,stun:0,contactCooldown:0,lane:r.kind==='calm'?2:0};});}
export function resetCar(t,c){const p=at(t,c.lastS);c.x=p.x+p.nx*c.lane;c.z=p.z+p.nz*c.lane;c.heading=p.heading;c.vx=0;c.vz=0;c.stuck=0;c.stun=0;c.contactCooldown=0;}
export function botInput(t,c,cars=[]){const speed=Math.hypot(c.vx,c.vz),p=nearest(t,c.x,c.z),aim=at(t,p.s+7+speed*.4);let tx=aim.x+aim.nx*c.lane,tz=aim.z+aim.nz*c.lane;const others=cars.filter(v=>v!==c&&!v.finished).sort((a,b)=>Math.hypot(a.x-c.x,a.z-c.z)-Math.hypot(b.x-c.x,b.z-c.z));const target=others[0];let attacking=false;if(c.kind==='aggressive'&&target&&Math.hypot(target.x-c.x,target.z-c.z)<18){const dx=target.x-c.x,dz=target.z-c.z;if(dx*Math.cos(c.heading)+dz*Math.sin(c.heading)>-3){tx=target.x+target.vx*.35;tz=target.z+target.vz*.35;attacking=true;}}
if(c.kind==='calm'&&target&&Math.hypot(target.x-c.x,target.z-c.z)<7){const side=(target.x-p.x)*p.nx+(target.z-p.z)*p.nz;tx=aim.x+aim.nx*(side>0?-2.5:2.5);tz=aim.z+aim.nz*(side>0?-2.5:2.5);}
const err=angle(Math.atan2(tz-c.z,tx-c.x)-c.heading),limit=c.kind==='calm'?25:attacking?34:32;c.attacking=attacking;return{gas:speed>limit?0:Math.abs(err)>1?.35:1,brake:speed>limit+1||speed>25&&Math.abs(err)>1.1?.3:0,steer:clamp(err*2,-1,1),drift:attacking&&Math.abs(err)>.7};}
export function step(t,cars,input,dt,time,onHit=()=>{}){for(const c of cars){c.stun=Math.max(0,(c.stun||0)-dt);c.contactCooldown=Math.max(0,(c.contactCooldown||0)-dt);const u={...(c.kind==='player'?(input.players?.[c.id]||input):botInput(t,c,cars))},p=nearest(t,c.x,c.z);if(c.jammed)u.steer=clamp(u.steer*(Math.sin(time*5+c.id)>0?1:-1)+Math.sin(time*11+c.id*7)*.65,-1,1);let fx=Math.cos(c.heading),fz=Math.sin(c.heading),forward=c.vx*fx+c.vz*fz,lateral=-c.vx*fz+c.vz*fx;const off=p.distance>t.width/2-.8,grip=c.stun>0?1.8:u.drift?1.5:off?3:9;const turn=clamp(forward/7,-1,1)*2.05*(u.drift?1.2:1)/(1+Math.abs(forward)*.012);c.heading+=u.steer*turn*dt;fx=Math.cos(c.heading);fz=Math.sin(c.heading);forward=c.vx*fx+c.vz*fz;lateral=-c.vx*fz+c.vz*fx;const boost=c.kind==='player'&&u.boost,drag=(off?1.8:.35)+(c.stun>0?1.35:0)+(c.syrup?3:0)+(c.cashSlow?1.7:0);forward+=(u.gas*(boost?36:c.kind==='player'?17:c.kind==='aggressive'?25:22)*(c.stun>0?.3:1)*(c.syrup?.4:1)*(c.cashSlow?.5:1)-u.brake*(forward>1?28:10)-forward*drag-forward*Math.abs(forward)*.007)*dt;forward=clamp(forward,-7,boost?47:c.kind==='player'?29:c.kind==='aggressive'?35:32);lateral*=Math.exp(-grip*dt);fx=Math.cos(c.heading);fz=Math.sin(c.heading);c.vx=fx*forward-fz*lateral;c.vz=fz*forward+fx*lateral;if(c.hardStop||c.crossing){c.vx=c.vz=0;}c.x+=c.vx*dt;c.z+=c.vz*dt;
const wall=nearest(t,c.x,c.z),limit=t.width/2+2.5;if(wall.distance>limit){const nx=(c.x-wall.x)/wall.distance,nz=(c.z-wall.z)/wall.distance;c.x=wall.x+nx*limit;c.z=wall.z+nz*limit;const vn=c.vx*nx+c.vz*nz;if(vn>0){c.vx-=vn*1.35*nx;c.vz-=vn*1.35*nz;if(vn>3)onHit(c,null,vn);}}
const now=nearest(t,c.x,c.z);let delta=now.s-c.lastS;if(delta>t.length/2)delta-=t.length;if(delta<-t.length/2)delta+=t.length;if(Math.abs(delta)<4){c.progress+=delta;}c.lastS=now.s;c.lap=Math.max(0,Math.floor(c.progress/t.length));if(c.lap>=3&&!c.finished){c.finished=true;c.finishTime=time;}
if(c.kind!=='player'&&Math.hypot(c.vx,c.vz)<2)c.stuck+=dt;else c.stuck=0;if(c.stuck>3)resetCar(t,c);}
// Equal-mass contact impulses preserve a real shove, plus overlap correction.
for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){const a=cars[i],b=cars[j],dx=b.x-a.x,dz=b.z-a.z,dist=Math.hypot(dx,dz),radius=2.35;if(dist>=radius)continue;const nx=dist>.001?dx/dist:1,nz=dist>.001?dz/dist:0,push=(radius-dist)/2+.001;a.x-=nx*push;a.z-=nz*push;b.x+=nx*push;b.z+=nz*push;const approachA=a.vx*nx+a.vz*nz,approachB=-(b.vx*nx+b.vz*nz),striker=approachA>approachB?a:b;const rel=(b.vx-a.vx)*nx+(b.vz-a.vz)*nz;if(rel<0){const impulse=-rel*.95;a.vx-=impulse*nx;a.vz-=impulse*nz;b.vx+=impulse*nx;b.vz+=impulse*nz;if(rel<-2){
const victim=striker===a?b:a;
if(victim.contactCooldown<=0){const sign=victim===b?1:-1,kick=clamp(-rel*.65,3,10)*(striker.kind==='aggressive'?1.65:1);victim.vx+=nx*sign*kick;victim.vz+=nz*sign*kick;victim.stun=.7;victim.contactCooldown=.85;}
onHit(a,b,-rel); }}}}
