import {batchStatic} from './batching.js?v=3';
import * as T from './three.module.js';
import {at,nearest,random} from './engine.js';
// Country scenery and event visuals are independent from the driving simulation.
export class LocationView{
 constructor(scene,track,country){this.scene=scene;this.track=track;this.country=country;this.group=new T.Group();scene.add(this.group);this.live=new Map();this.signs=[];this.materials=new Map();this.geometry=new Set();this.textures=[];this.money=[];this.fires=[];this.visualTime=0;this.build();const moving=new Set(this.signs);if(this.eye)moving.add(this.eye);for(const f of this.fires)for(const m of [...f.flames,...f.smoke])moving.add(m);this.batchStats=batchStatic(this.group,moving,this.geometry);}
 mat(color,glow=false){const key=color+glow;if(!this.materials.has(key))this.materials.set(key,new T.MeshStandardMaterial({color,roughness:glow?.35:.78,emissive:glow?color:'#000000',emissiveIntensity:glow?1.4:0}));return this.materials.get(key);}
 mesh(geo,color,x,y,z,parent=this.group,glow=false){this.geometry.add(geo);const m=new T.Mesh(geo,this.mat(color,glow));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(w,h,d,c,x,y,z,p=this.group,glow=false){return this.mesh(new T.BoxGeometry(w,h,d),c,x,y,z,p,glow);}
 ball(r,c,x,y,z,p=this.group){return this.mesh(new T.SphereGeometry(r,10,7),c,x,y,z,p);}
 label(text,x,y,z,w=10,parent=this.group,color='#f7f1dc'){let mat=this.materials.get('label:'+text);if(!mat){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#151822';ctx.fillRect(0,0,512,128);ctx.fillStyle=color;ctx.font='bold 54px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,68,480);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;this.textures.push(tex);mat=new T.MeshBasicMaterial({map:tex,side:T.DoubleSide});this.materials.set('label:'+text,mat);}const geo=new T.PlaneGeometry(w,w/4);this.geometry.add(geo);const m=new T.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);this.signs.push(m);return m;}
 windows(g,w,h,d,color,lit=false){const n=Math.floor(h/2),cols=Math.floor(w/1.5),geo=new T.BoxGeometry(.65,.8,.08);this.geometry.add(geo);const m=new T.InstancedMesh(geo,this.mat(color,lit),n*cols*2),matrix=new T.Matrix4();let k=0;for(const z of [-d/2-.05,d/2+.05])for(let row=0;row<n;row++)for(let col=0;col<cols;col++){matrix.makeTranslation((col-(cols-1)/2)*1.5,1+row*2,z);m.setMatrixAt(k++,matrix);}g.add(m);}
 building(x,z,w,h,d,color,kind){const g=new T.Group();g.position.set(x,0,z);this.group.add(g);if(kind==='ru'){for(let k=0;k<3;k++)this.box(w,h/3-.12,d,k%2?'#858992':color,0,(k+.5)*h/3,0,g);}else if(kind==='ruin'){this.box(w*.4,h,d,color,-w*.3,h/2,0,g);this.box(w*.55,h*.55,d,color,w*.2,h*.275,0,g);for(let k=0;k<7;k++){const m=this.box(1.2,.6,.9,'#696762',w*.3+(k%3)-1,.3,d*.6+Math.floor(k/3));m.rotation.y=k;g.add(m);}for(let k=0;k<3;k++)this.box(.12,h*.35,.12,'#343b43',w*.2+k*.5,h*.67,0,g);}else this.box(w,h,d,color,0,h/2,0,g);
 if(kind!=='ruin')this.windows(g,w,h,d,kind==='sg'?'#50e8e0':'#303e4c',kind==='sg');
 if(kind==='sg'){for(let y=3;y<h;y+=3)this.box(w+.22,.09,d+.22,y%2?'#ab45ef':'#37ddf1',0,y,0,g,true);this.box(w+.15,.12,d+.15,'#d04ce4',0,h,0,g,true);this.box(.12,h,d+.12,'#28a7d5',w/2,h/2,0,g,true);}
 if(kind==='house'){const roof=this.mesh(new T.CylinderGeometry(w*.78,w*.78,d+1,3),'#be5b43',0,h+.8,0,g);roof.rotation.z=Math.PI/2;roof.rotation.y=Math.PI/2;}
 return g;}
 fire(x,z){const g=new T.Group();g.position.set(x,0,z);this.group.add(g);const flames=[];for(let i=0;i<5;i++){const m=this.mesh(new T.ConeGeometry(.65,2.8,7),i%2?'#ffb52e':'#ee5920',(i%3-1)*.65,1.2,Math.floor(i/3)*.5,g,true);flames.push(m);}const smoke=[];for(let i=0;i<4;i++){const m=this.ball(1.1,'#35373b',0,3+i*1.4,0,g);smoke.push(m);}this.fires.push({flames,smoke});}
 fence(x,z){const g=new T.Group();g.position.set(x,0,z);this.group.add(g);for(let i=0;i<15;i++)this.box(.09,3.5,.09,'#343c40',i*.55-4,1.75,0,g);for(const y of [.5,2.8,3.5])this.box(8,.09,.09,'#596366',0,y,0,g);for(let i=0;i<7;i++){const m=this.mesh(new T.TorusGeometry(.36,.025,3,9),'#707979',i*1.15-3.5,3.7,0,g);m.rotation.y=.4;}return g;}
 flag(x,z){let mat=this.materials.get('flag');if(!mat){const tex=new T.TextureLoader().load('./flags/'+this.country.id+'.png');tex.colorSpace=T.SRGBColorSpace;this.textures.push(tex);mat=new T.MeshBasicMaterial({map:tex,side:T.DoubleSide});this.materials.set('flag',mat);}this.box(.12,6,.12,'#aeb5ba',x,3,z);const geo=new T.PlaneGeometry(3,1.8);this.geometry.add(geo);const m=new T.Mesh(geo,mat);m.position.set(x+1.5,5,z);this.group.add(m);}
 build(){const id=this.country.id,r=random(this.track.seed+'countryScene');
 for(let i=0;i<14;i++){const p=at(this.track,i/14*this.track.length),side=i%2?1:-1,off=side*(17+r()*6),x=p.x+p.nx*off,z=p.z+p.nz*off;if(nearest(this.track,x,z).distance<13)continue;const h=5+r()*9;
 if(id==='ca'){this.building(x,z,5,4,5,i%2?'#a35b40':'#af4d42','house');this.box(1.2,.1,2,'#eee7d9',x,4.2,z);}
 if(id==='rs'){this.building(x,z,5,h*.55,5,['#d9bc91','#e0c8ad','#bc8e72'][i%3],'house');}
 if(id==='ua'){this.building(x,z,6,h,5,i%3?'#a7aaa0':'#c8bb9f',i%3===0?'ruin':'normal');if(i%3===0){const crater=this.mesh(new T.CylinderGeometry(2,1.5,.15,14),'#303537',x+4,.02,z+4);crater.rotation.z=.07;this.fire(x+2,z+3);}}
 if(id==='ru'){this.building(x,z,7,h+3,5,i%2?'#848989':'#686f76','ru');this.fence(x,z+3.5);for(let k=0;k<5;k++)this.box(.08,h+3,.12,'#353b40',x+k*1.2-2.4,(h+3)/2,z+2.7);}
 if(id==='sg'){this.building(x,z,5,h+5,5,['#242845','#283952','#3b2b51'][i%3],'sg');const ring=this.mesh(new T.TorusGeometry(2,.09,5,24),'#ed59d8',x,h+7,z,this.group,true);ring.rotation.x=Math.PI/2;}
 if(r()<.18)this.flag(x+4,z);
 }
 if(id==='ca'){for(let i=0;i<4;i++)this.mesh(new T.CylinderGeometry(1.1,1.1,2.4,12),'#aa7440',i*3-4.5,1.2,0);}
 if(id==='rs'){this.label('ĆEVAPI',0,5,0,13);this.box(10,3,5,'#b6583e',0,1.5,0);this.box(11,.4,6,'#e8cd8f',0,3.2,0);this.box(6,.3,2,'#383439',0,2,3);for(let i=0;i<9;i++){const m=this.mesh(new T.CapsuleGeometry(.2,.8,3,7),'#804b2d',-2+i*.5,2.35,3);m.rotation.z=Math.PI/2;}}
 if(id==='ua'){for(let i=0;i<7;i++)this.box(1.5,.7,1,'#817b68',i*1.5-5,.35,3);this.building(-4,-2,6,7,5,'#77786e','ruin');this.fire(0,1);}
 if(id==='ru'){this.eye=new T.Group();this.group.add(this.eye);const eye=this.mesh(new T.SphereGeometry(1,20,12),'#e4dbbf',0,0,0,this.eye);eye.scale.set(5,2.1,1.5);this.ball(1.6,'#b84342',0,0,1.3,this.eye);this.ball(.85,'#151722',0,0,2.3,this.eye);for(const z of [-7,7])this.fence(0,z);for(const x of [-10,10]){this.box(1,8,1,'#555e61',x,4,0);this.box(4,2,4,'#777d78',x,8,0);this.box(4.5,.3,4.5,'#404949',x,9.2,0);}}
 if(id==='sg'){for(let i=0;i<3;i++)this.box(4,12,4,'#253548',i*7-7,6,0);this.box(22,1.5,6,'#8e48ac',0,12,0,this.group,true);for(let i=0;i<5;i++)this.box(.15,8,.15,'#43ddd9',i*3-6,4,8,this.group,true);}
 }
 eventMesh(e){const g=new T.Group();this.group.add(g);const parts={g};
 if(e.type==='syrup'){const m=this.mesh(new T.CircleGeometry(4.7,24),'#a95b19',0,.07,0,g);m.rotation.x=-Math.PI/2;this.mesh(new T.CylinderGeometry(.7,.8,1.5,12),'#ba813a',4,.7,0,g).rotation.z=1;parts.pool=m;}
 if(e.type==='students'){parts.people=[];for(let i=0;i<7;i++){const person=new T.Group();g.add(person);this.mesh(new T.CapsuleGeometry(.27,.6,3,7),['#e9bf59','#d2d9e5','#b56589'][i%3],0,.85,0,person);this.ball(.27,'#e5bea3',0,1.6,0,person);const legs=[];for(const side of [-1,1])legs.push(this.box(.16,.5,.18,'#374254',side*.16,.28,0,person));if(i%2===0){this.box(.07,1.1,.07,'#b29a75',.4,1.3,0,person);this.label(i%4?'INDEKS':'STUDENTI',.4,2,0,1.8,person); }parts.people.push({person,legs});}}
 if(e.type==='missile'){parts.marker=this.mesh(new T.RingGeometry(5.5,5.9,40),'#f7593c',0,.09,0,g,true);parts.marker.rotation.x=-Math.PI/2;parts.rocket=new T.Group();g.add(parts.rocket);this.mesh(new T.CylinderGeometry(.27,.32,2.5,10),'#677480',0,0,0,parts.rocket);this.mesh(new T.ConeGeometry(.32,.7,10),'#e5a249',0,-1.55,0,parts.rocket).rotation.z=Math.PI;parts.blast=this.ball(1,'#ffad3c',0,1,0,g);parts.blast.material=this.mat('#ff912e',true);parts.smoke=[];for(let i=0;i<5;i++)parts.smoke.push(this.ball(1,'#4d535c',Math.cos(i*1.26)*2,1,Math.sin(i*1.26)*2,g));}
 if(e.type==='police'){this.box(1.9,.55,3.2,'#e6e8ed',0,.7,0,g);this.box(1.5,.5,1.5,'#2b3c5d',0,1.18,0,g);this.box(2,.16,2.8,'#396ac1',0,.75,0,g);parts.red=this.box(.55,.17,.35,'#ec3f4c',-.4,1.55,0,g,true);parts.blue=this.box(.55,.17,.35,'#4c93ff',.4,1.55,0,g,true);for(const x of [-.9,.9])for(const z of [-1,1])this.ball(.38,'#23232c',x,.36,z,g);}
 if(e.type==='drone'){parts.body=new T.Group();g.add(parts.body);this.box(2,.25,.3,'#444957',0,0,0,parts.body);this.box(.3,.25,2,'#444957',0,0,0,parts.body);parts.rotors=[];for(const x of [-1,1])for(const z of [-1,1])parts.rotors.push(this.box(1.1,.05,.12,'#15171c',x,.1,z,parts.body));parts.shadow=this.mesh(new T.RingGeometry(2.8,3.1,24),'#bb538a',0,.08,0,g,true);parts.shadow.rotation.x=-Math.PI/2;}
 if(e.type==='pigeons'){parts.birds=[];for(let i=0;i<5;i++){const bird=new T.Group();g.add(bird);this.ball(.33,'#8e9bad',0,.4,0,bird);this.ball(.2,'#80978f',0,.7,.25,bird);this.mesh(new T.ConeGeometry(.09,.25,5),'#cfb15e',0,.65,.45,bird).rotation.x=Math.PI/2;const wings=[];for(const side of [-1,1]){const m=this.ball(.3,'#5a637a',side*.32,.45,0,bird);m.scale.set(1.4,.2,1);wings.push(m);}parts.birds.push({bird,wings});}}
 this.live.set(e.id,parts);return parts;}
 emit(type,c,e){if(type!=='money')return;for(let i=0;i<14;i++){const m=this.box(.5,.025,.25,i%2?'#91cc79':'#e6d99c',c.x,.8,c.z);this.money.push({m,life:1.8,vx:(i%4-1.5)*2,vz:(Math.floor(i/4)-1.5)*2,vy:4+i%3});}}
 update(events,time,dt,camera){this.visualTime+=dt;const vt=this.visualTime;if(this.eye){this.eye.position.set(Math.sin(vt*.22)*11,13+Math.sin(vt*.85)*1.5,Math.cos(vt*.22)*8);this.eye.lookAt(camera.position);}for(const f of this.fires){f.flames.forEach((m,i)=>{m.scale.y=.8+Math.sin(vt*9+i*2)*.22;m.rotation.y=vt*.7+i;});f.smoke.forEach((m,i)=>{m.position.x=Math.sin(vt*.8+i)*.6+i*.25;m.scale.setScalar(1+i*.2+Math.sin(vt*1.5+i)*.12);});}const ids=new Set(events.items.map(e=>e.id));for(const[id,v]of this.live)if(!ids.has(id)){this.group.remove(v.g);const retired=new Set();v.g.traverse(m=>{retired.add(m);if(m.geometry){m.geometry.dispose();this.geometry.delete(m.geometry);}});this.live.delete(id);this.signs=this.signs.filter(m=>!retired.has(m));}
 for(const e of events.items){const v=this.live.get(e.id)||this.eventMesh(e),a=time-e.born;v.g.position.set(e.x,0,e.z);
 if(e.type==='syrup'){v.pool.scale.setScalar(Math.min(1,a));}
 if(e.type==='students'){for(let i=0;i<v.people.length;i++){const p=v.people[i],walk=-11+Math.min(1,Math.max(0,(a-1)/5.8))*22;p.person.position.set(-Math.sin(e.heading)*walk+Math.cos(e.heading)*(i%3-1)*1.1,0,Math.cos(e.heading)*walk+Math.sin(e.heading)*(i%3-1)*1.1+(Math.floor(i/3)-1)*.55);for(let j=0;j<2;j++)p.legs[j].rotation.x=Math.sin(a*10+i+j*Math.PI)*.5;}}
 if(e.type==='missile'){v.marker.visible=a<2.7;v.marker.scale.setScalar(1+Math.sin(a*9)*.04);v.rocket.visible=a>1.8&&a<2.7;v.rocket.position.y=Math.max(0,(2.7-a)*32);const b=Math.max(0,a-2.7);v.blast.visible=b>0&&b<.55;v.blast.scale.setScalar(.3+b*13);for(let i=0;i<v.smoke.length;i++){const m=v.smoke[i];m.visible=b>0;m.position.y=1+b*4;m.scale.setScalar(.6+b*1.6);}}
 if(e.type==='police'){v.g.rotation.y=Math.PI/2-e.heading;v.red.visible=Math.sin(a*20)>0;v.blue.visible=!v.red.visible;}
 if(e.type==='drone'){v.body.position.y=6+Math.sin(a*3)*.4;for(const m of v.rotors)m.rotation.y=a*45;}
 if(e.type==='pigeons'){for(let i=0;i<v.birds.length;i++){const b=v.birds[i];b.bird.position.set((i%3-1)*1.1,Math.max(0,1.3-a)*5,Math.floor(i/3)*1.2);for(let j=0;j<2;j++)b.wings[j].rotation.z=Math.sin(a*14+i)*(a<1.3?.7:.13)*(j?1:-1);}}
 }
 for(let i=this.money.length-1;i>=0;i--){const p=this.money[i];p.life-=dt;p.vy-=7*dt;p.m.position.x+=p.vx*dt;p.m.position.z+=p.vz*dt;p.m.position.y+=p.vy*dt;p.m.rotation.z+=dt*5;if(p.life<=0){this.group.remove(p.m);p.m.geometry.dispose();this.geometry.delete(p.m.geometry);this.money.splice(i,1);}}
 for(const m of this.signs)m.quaternion.copy(camera.quaternion);
 }
 dispose(){this.scene.remove(this.group);for(const g of this.geometry)g.dispose();for(const m of this.materials.values())m.dispose();for(const t of this.textures)t.dispose();}
}
