// Firebase only introduces peers; race traffic uses an unordered WebRTC channel.
export class RacePeers{
 constructor({host,tab,uid,path,ref,db,onValue,set,onInput,onSnapshot,participants}){Object.assign(this,{host,tab,uid,path,ref,db,onValue,set,onInput,onSnapshot,participants});this.links=new Map();this.stops=[];this.closed=false;}
 get connected(){return [...this.links.values()].some(p=>p.ch?.readyState==='open'&&Date.now()-(p.lastReceived||p.openedAt||0)<2000);}
 send(p,data){if(p?.ch?.readyState!=='open'||p.ch.bufferedAmount>65536)return false;try{p.ch.send(JSON.stringify(data));return true;}catch{return false;}}
 broadcast(data){for(const p of this.links.values())this.send(p,{type:'snapshot',data});}
 input(data){if(!this.connected)return false;return this.send(this.links.get('host'),{type:'input',data});}
 async gather(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const finish=()=>{clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',check);resolve();},check=()=>{if(pc.iceGatheringState==='complete')finish();},timer=setTimeout(finish,8000);pc.addEventListener('icegatheringstatechange',check);});}
 peer(key,member,driver){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});const p={pc,member,driver};this.links.set(key,p);const attach=ch=>{p.ch=ch;ch.onopen=()=>p.openedAt=Date.now();ch.onmessage=e=>{p.lastReceived=Date.now();if(this.closed||typeof e.data!=='string'||e.data.length>100000)return;let m;try{m=JSON.parse(e.data);}catch{return;}if(this.host&&m.type==='input'&&this.participants()[member]?.driver===driver)this.onInput(member,m.data);if(!this.host&&m.type==='snapshot')this.onSnapshot(m.data);};};pc.ondatachannel=e=>attach(e.channel);p.attach=attach;return p;}
 async start(){if(typeof RTCPeerConnection==='undefined')return;try{if(this.host){this.stops.push(this.onValue(this.ref(this.db,this.path+'/signals'),snap=>{for(const [key,v]of Object.entries(snap.val()||{})){if(this.links.has(key)||!v.offer||typeof v.uid!=='string'||this.links.size>=24)continue;const p=this.peer(key,v.uid,key);(async()=>{await p.pc.setRemoteDescription(v.offer);await p.pc.setLocalDescription(await p.pc.createAnswer());await this.gather(p.pc);if(!this.closed)await this.set(this.ref(this.db,this.path+'/signals/'+key+'/answer'),p.pc.localDescription.toJSON());})().catch(()=>{});}}));}else{const p=this.peer('host');p.attach(p.pc.createDataChannel('race',{ordered:false,maxRetransmits:0}));await p.pc.setLocalDescription(await p.pc.createOffer());await this.gather(p.pc);if(this.closed)return;this.stops.push(this.onValue(this.ref(this.db,this.path+'/signals/'+this.tab+'/answer'),snap=>{const a=snap.val();if(a&&!p.answering&&!p.pc.remoteDescription){p.answering=true;p.pc.setRemoteDescription(a).catch(()=>{});}}));await this.set(this.ref(this.db,this.path+'/signals/'+this.tab),{uid:this.uid,offer:p.pc.localDescription.toJSON()});}}catch{/* Firebase remains the fallback. */}}
 close(){this.closed=true;for(const stop of this.stops)stop();for(const p of this.links.values())p.pc.close();this.links.clear();}
}
