// Uses the room's existing authenticated Firebase connection. No new credentials.
export function installRace3D({db,auth,state,basePath,ref,onValue,get,set,update,remove,runTransaction,uid,isOverlay,enabled}){
 const tab=crypto.randomUUID(),root=ref(db,`${basePath}/games/active`),color=c=>/^#[0-9a-f]{6}$/i.test(c||'')?c:'#16c7b7';
 let game=null,frame=null,panel=null,ready=false,unsubs=[],inputBusy=false,snapshotBusy=false,lastSignal=Date.now(),lastSeq=-1,ending=false,closedId=null;
 const amHost=()=>game?.driver===tab&&game?.host===uid();
 const send=m=>{if(ready&&frame)frame.contentWindow.postMessage({dpRace:1,id:game.id,...m},location.origin);};
 const stream=()=>`${basePath}/games/race3d/${game.id}`;
 const fail=e=>{console.warn('[race3d]',e);if(panel)panel.textContent='Не удалось связаться с игрой. Обнови страницу.';};
 function close(){for(const f of unsubs)f();unsubs=[];frame?.remove();panel?.remove();frame=panel=null;ready=false;ending=false;lastSeq=-1;document.body.classList.remove('race3d-active');if(isOverlay())console.log('[DUEL_INTERACTIVE_OFF]');}
 function roster(){return game.order.map(id=>({uid:id,color:color(game.participants[id]?.color)}));}
 function initialize(){if(!ready||!game?.order)return;const own=game.order.indexOf(uid());send({type:'init',seed:game.seed,roster:roster(),localId:own>=0?own:Math.max(0,game.order.indexOf(game.host)),canDrive:own>=0&&game.participants[uid()]?.driver===tab,authority:amHost(),bots:game.bots||{},duration:180});}
 function openFrame(){if(frame)return;frame=document.createElement('iframe');frame.src='./race3d/index.html?v=1';frame.title='Гонки';frame.allow='autoplay';frame.style.cssText='position:fixed;inset:0;width:100%;height:100%;border:0;z-index:100040;background:#151823';document.body.append(frame);document.body.classList.add('race3d-active');if(isOverlay())console.log('[DUEL_INTERACTIVE_ON]');lastSignal=Date.now();
 const path=stream();
 if(amHost())unsubs.push(onValue(ref(db,path+'/inputs'),snap=>send({type:'inputs',inputs:snap.val()||{}})));
 else unsubs.push(onValue(ref(db,path+'/snapshot'),snap=>{const data=snap.val();if(data&&Number.isInteger(data.seq)&&data.seq>lastSeq){lastSeq=data.seq;lastSignal=Date.now();send({type:'snapshot',data});}}));
 }
 function renderLobby(){if(!panel){panel=document.createElement('section');panel.style.cssText='position:fixed;top:18%;left:50%;transform:translateX(-50%);z-index:100045;background:#191c26;color:#eee;border:1px solid #656777;border-radius:18px;padding:20px;max-width:90vw;min-width:260px;font:16px Segoe UI,sans-serif';document.body.append(panel);}
 panel.replaceChildren();const title=document.createElement('h3');title.textContent='Гонки';title.style.margin='0 0 12px';panel.append(title);const dots=document.createElement('div');dots.style.cssText='display:flex;gap:10px;margin-bottom:14px';for(const p of Object.values(game.participants||{})){const dot=document.createElement('span');dot.style.cssText=`display:inline-block;width:22px;height:22px;border-radius:50%;background:${color(p.color)}`;dots.append(dot);}panel.append(dots);
 const button=(text,fn)=>{const b=document.createElement('button');b.textContent=text;b.style.cssText='padding:8px 12px;border-radius:9px;margin:5px;border:1px solid #656777;background:#303444;color:#fff;cursor:pointer';b.onclick=()=>Promise.resolve(fn()).catch(fail);panel.append(b);};
 if(!game.participants?.[uid()])button('Вписаться',join);
 if(amHost()){for(const [id,name]of [['calm','Виталик'],['aggressive','Вадя']]){const label=document.createElement('label');label.style.marginRight='12px';label.append(name+' ');const cb=document.createElement('input');cb.type='checkbox';cb.checked=game.bots?.[id]!==false;cb.onchange=()=>update(root,{['bots/'+id]:cb.checked}).catch(fail);label.append(cb);panel.append(label);}button('Старт',start);button('Отменить',()=>remove(root));}
 else{const text=document.createElement('p');text.textContent='Стартует создатель заезда';panel.append(text);}
 }
 async function create(){if(!auth.currentUser||!uid())return;const now=Date.now();const next={type:'race',engine:'3d-v1',id:crypto.randomUUID(),seed:crypto.randomUUID(),host:uid(),driver:tab,state:'lobby',startedAt:now,bots:{calm:true,aggressive:true},participants:{[uid()]:{color:color(state.color),driver:tab}}};const result=await runTransaction(root,v=>v&&v.state!=='ended'&&now-(v.startedAt||now)<600000?undefined:next);if(!result.committed)alert('Уже идёт игра, дождитесь окончания');}
 async function join(){const id=game?.id,me=uid();if(!me)return;await runTransaction(root,v=>{if(v?.id!==id||v.state!=='lobby'||v.participants?.[me]||Object.keys(v.participants||{}).length>=12)return;v.participants={...v.participants,[me]:{color:color(state.color),driver:tab}};return v;});}
 async function start(){if(!amHost())return;const id=game.id;await runTransaction(root,v=>{if(v?.id!==id||v.state!=='lobby')return;const order=[v.host,...Object.keys(v.participants).filter(p=>p!==v.host).sort()];if(order.length<2&&!v.bots.calm&&!v.bots.aggressive)return;return{...v,order,state:'racing',racingStartedAt:Date.now()};});}
 async function end(data){if(!amHost()||ending)return;ending=true;const id=game.id;const humans=data.cars.filter(c=>c.kind==='player'),order=humans.filter(c=>c.finished).sort((a,b)=>a.finishTime-b.finishTime).map(c=>game.order[c.id]);await runTransaction(root,v=>v?.id===id&&v.state==='racing'?{...v,state:'ended',endedAt:Date.now(),finishOrder:order,winner:order[0]||null}:undefined);setTimeout(async()=>{await runTransaction(root,v=>v?.id===id?null:undefined);await remove(ref(db,`${basePath}/games/race3d/${id}`));},10000);}
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow||e.data?.dpRace!==1)return;const m=e.data;if(m.type==='ready'){ready=true;initialize();return;}if(!game||m.id!==game.id)return;
 if(m.type==='input'&&game.participants?.[uid()]?.driver===tab&&!inputBusy){inputBusy=true;set(ref(db,stream()+'/inputs/'+uid()),{gas:m.input?.gas===1?1:0,brake:m.input?.brake===1?1:0,steer:[-1,0,1].includes(m.input?.steer)?m.input.steer:0,drift:m.input?.drift===true,boost:m.input?.boost===true,reset:Number.isSafeInteger(m.input?.reset)?m.input.reset:0,t:Date.now()}).catch(fail).finally(()=>inputBusy=false);}
 if(m.type==='snapshot'&&amHost()&&!snapshotBusy){snapshotBusy=true;lastSignal=Date.now();const data=JSON.parse(JSON.stringify(m.data));data.sentAt=Date.now();set(ref(db,stream()+'/snapshot'),data).then(()=>{if(data.done)return end(data);}).catch(fail).finally(()=>snapshotBusy=false);}
 });
 if(enabled)onValue(root,snap=>{const v=snap.val();if(v?.type!=='race'||v.engine!=='3d-v1'){if(game)close();game=null;return;}if(game?.id!==v.id){close();closedId=null;}game=v;if(closedId===v.id)return;if(v.state==='lobby')renderLobby();else{panel?.remove();panel=null;openFrame();}});
 setInterval(()=>{if(!game||game.state==='lobby'||!frame)return;if(Date.now()-lastSignal>15000&&game.state!=='ended'){send({type:'stalled'});if(Date.now()-lastSignal>45000){const id=game.id;get(ref(db,stream()+'/snapshot')).then(s=>{const d=s.val();if(!d?.sentAt||Date.now()-d.sentAt>40000)return runTransaction(root,v=>v?.id===id&&v.state==='racing'?{...v,state:'ended',endedAt:Date.now()}:undefined);}).catch(fail);closedId=id;close();}}},1000);
 window.addEventListener('pagehide',()=>{close();});
 return{create,join,start};
}
